name: property_manager
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres_image
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DB}
    networks:
      - property_manager-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PG_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PG_PASSWORD}"
      SCRIPT_NAME: /pgadmin
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - 5050:80
    networks:
      - property_manager-network
  python-app:
    build:
      dockerfile: Dockerfile
    container_name: property_manager
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - property_manager-network
    environment:
      - PG_DB=${PG_DB}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_HOST=postgres
      - PG_PORT=5432
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS}
networks:
  property_manager-network:
    driver: bridge
volumes:
  postgres:
  pgadmin:
