"""Extend model for property manager

Revision ID: 3f7d8fd625b6
Revises: 42ee39593c9e
Create Date: 2025-02-02 18:11:40.245164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f7d8fd625b6'
down_revision: Union[str, None] = '42ee39593c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_managers', sa.Column('firstname', sa.String(), nullable=False))
    op.add_column('property_managers', sa.Column('surname', sa.String(), nullable=False))
    op.add_column('property_managers', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('property_managers', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_managers', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('property_managers', 'title')
    op.drop_column('property_managers', 'surname')
    op.drop_column('property_managers', 'firstname')
    # ### end Alembic commands ###
