"""Extend model for property

Revision ID: 61211887c12a
Revises: 3f7d8fd625b6
Create Date: 2025-02-02 18:28:58.869580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61211887c12a'
down_revision: Union[str, None] = '3f7d8fd625b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'property_manager_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'property_manager_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
