"""Initial model

Revision ID: 87978f357ec8
Revises: 
Create Date: 2025-03-16 15:53:00.424099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "87978f357ec8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addresses",
        sa.Column("street", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("postal_code", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_addresses_city"), "addresses", ["city"], unique=False)
    op.create_index(op.f("ix_addresses_country"), "addresses", ["country"], unique=False)
    op.create_index(op.f("ix_addresses_postal_code"), "addresses", ["postal_code"], unique=False)
    op.create_index(op.f("ix_addresses_state"), "addresses", ["state"], unique=False)
    op.create_index(op.f("ix_addresses_street"), "addresses", ["street"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "property_managers",
        sa.Column("firstname", sa.String(), nullable=False),
        sa.Column("surname", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "tenants",
        sa.Column("firstname", sa.String(), nullable=False),
        sa.Column("surname", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("date_of_birth", sa.DateTime(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenants_email"), "tenants", ["email"], unique=False)
    op.create_index(op.f("ix_tenants_firstname"), "tenants", ["firstname"], unique=False)
    op.create_index(op.f("ix_tenants_phone"), "tenants", ["phone"], unique=False)
    op.create_index(op.f("ix_tenants_surname"), "tenants", ["surname"], unique=False)
    op.create_table(
        "guarantors",
        sa.Column("firstname", sa.String(), nullable=False),
        sa.Column("surname", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("date_of_birth", sa.DateTime(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=True),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_guarantors_email"), "guarantors", ["email"], unique=False)
    op.create_index(op.f("ix_guarantors_firstname"), "guarantors", ["firstname"], unique=False)
    op.create_index(op.f("ix_guarantors_phone"), "guarantors", ["phone"], unique=False)
    op.create_index(op.f("ix_guarantors_surname"), "guarantors", ["surname"], unique=False)
    op.create_table(
        "properties",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("address_id", sa.Integer(), nullable=True),
        sa.Column("property_manager_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["property_manager_id"],
            ["property_managers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_properties_name"), "properties", ["name"], unique=False)
    op.create_table(
        "inventories",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("property_id", sa.Integer(), nullable=False),
        sa.Column("rooms", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_inventories_name"), "inventories", ["name"], unique=False)
    op.create_table(
        "rentals",
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("rent_amount", sa.Integer(), nullable=False),
        sa.Column("deposit_amount", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("property_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payments",
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("rental_id", sa.Integer(), nullable=False),
        sa.Column("is_paid", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rental_id"],
            ["rentals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payments")
    op.drop_table("rentals")
    op.drop_index(op.f("ix_inventories_name"), table_name="inventories")
    op.drop_table("inventories")
    op.drop_index(op.f("ix_properties_name"), table_name="properties")
    op.drop_table("properties")
    op.drop_index(op.f("ix_guarantors_surname"), table_name="guarantors")
    op.drop_index(op.f("ix_guarantors_phone"), table_name="guarantors")
    op.drop_index(op.f("ix_guarantors_firstname"), table_name="guarantors")
    op.drop_index(op.f("ix_guarantors_email"), table_name="guarantors")
    op.drop_table("guarantors")
    op.drop_index(op.f("ix_tenants_surname"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_phone"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_firstname"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_email"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_table("property_managers")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_addresses_street"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_state"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_postal_code"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_country"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_city"), table_name="addresses")
    op.drop_table("addresses")
    # ### end Alembic commands ###
